// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlnYXdwKLsdkduyg4N3LdbZZYt5MKnA8o',
    appId: '1:585893187586:web:2cbf1390421b169397d71b',
    messagingSenderId: '585893187586',
    projectId: 'uraba-conecta',
    authDomain: 'uraba-conecta.firebaseapp.com',
    storageBucket: 'uraba-conecta.firebasestorage.app',
    measurementId: 'G-22QYE9Y1J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHJXiMbP9IWQcExnvpIsyezQ7b218se8Q',
    appId: '1:585893187586:android:fd9d74a1ea04597b97d71b',
    messagingSenderId: '585893187586',
    projectId: 'uraba-conecta',
    storageBucket: 'uraba-conecta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKwnQYtJ7nTXMdXHNSHPqDeOhzeX9gayQ',
    appId: '1:585893187586:ios:63796973eae4ce7697d71b',
    messagingSenderId: '585893187586',
    projectId: 'uraba-conecta',
    storageBucket: 'uraba-conecta.firebasestorage.app',
    iosBundleId: 'com.example.uraba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKwnQYtJ7nTXMdXHNSHPqDeOhzeX9gayQ',
    appId: '1:585893187586:ios:63796973eae4ce7697d71b',
    messagingSenderId: '585893187586',
    projectId: 'uraba-conecta',
    storageBucket: 'uraba-conecta.firebasestorage.app',
    iosBundleId: 'com.example.uraba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlnYXdwKLsdkduyg4N3LdbZZYt5MKnA8o',
    appId: '1:585893187586:web:fcb35fba429c849397d71b',
    messagingSenderId: '585893187586',
    projectId: 'uraba-conecta',
    authDomain: 'uraba-conecta.firebaseapp.com',
    storageBucket: 'uraba-conecta.firebasestorage.app',
    measurementId: 'G-7ZCRNTCHBX',
  );
}
